# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

target 'FlashCard' do
  config = use_native_modules!
  
  # Enable modular headers for Firebase pods that need it
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FlashCardTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Fix deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        end
        
        # Enable modular headers for Firebase Swift pods only
        if target.name.start_with?('Firebase') || target.name == 'GoogleUtilities'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
        
        # Fix FBReactNativeSpec header search paths for Xcode 17
        if target.name.start_with?('React-')
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"$(PODS_ROOT)/../build/generated/ios\""
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"${PODS_CONFIGURATION_BUILD_DIR}/FBReactNativeSpec/FBReactNativeSpec.framework/Headers\""
        end
      end
    end
    
    # Fix Firebase linking issues - remove weak framework references
    installer.pods_project.targets.each do |target|
      if target.name == 'Pods-FlashCard'
        target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          # Remove weak_framework references for Firebase pods
          xcconfig = xcconfig.gsub(/-weak_framework "FirebaseFirestoreInternal"/, '')
          xcconfig = xcconfig.gsub(/-weak_framework "FirebaseCore"/, '')
          xcconfig = xcconfig.gsub(/-weak_framework "FirebaseCoreExtension"/, '')
          File.write(xcconfig_path, xcconfig)
        end
      end
    end
  end
end
