# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FlashCard' do
  config = use_native_modules!

  # Enable modular headers for Firebase pods that need it
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FlashCardTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        end

        # Enable modular headers for Firebase Swift pods only
        if target.name.start_with?('Firebase') || target.name == 'GoogleUtilities'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end

        # Fix FBReactNativeSpec header search paths for Xcode 17
        if target.name.start_with?('React-')
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"$(PODS_ROOT)/../build/generated/ios\""
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"${PODS_CONFIGURATION_BUILD_DIR}/FBReactNativeSpec/FBReactNativeSpec.framework/Headers\""
        end
      end
    end

    # Fix Firebase linking issues - remove weak framework references
    installer.pods_project.targets.each do |target|
      if target.name == 'Pods-FlashCard'
        target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          # Remove weak_framework references for Firebase pods
          xcconfig = xcconfig.gsub(/-weak_framework "FirebaseFirestoreInternal"/, '')
          xcconfig = xcconfig.gsub(/-weak_framework "FirebaseCore"/, '')
          xcconfig = xcconfig.gsub(/-weak_framework "FirebaseCoreExtension"/, '')
          File.write(xcconfig_path, xcconfig)
        end
      end
    end
  end
end
